[theme]
primaryColor = "#012169"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F6FA"
textColor = "#001A52"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
